<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E3FNQHB" failures="1" tests="8" name="Api_tescase.TC004_Post_Employes_record_updated" time="0.026" errors="0" timestamp="2022-12-25T11:59:45 IST" skipped="0">
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="tear_down" time="0.001"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="checkResponsebody" time="0.007">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at Api_tescase.TC004_Post_Employes_record_updated.checkResponsebody(TC004_Post_Employes_record_updated.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkResponsebody -->
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="check_content_length" time="0.001"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="checkStatuscode" time="0.003"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="all_headers" time="0.008"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="checkContentType" time="0.003"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="checkStatusline" time="0.001"/>
  <system-out/>
  <testcase classname="Api_tescase.TC004_Post_Employes_record_updated" name="check_server_type" time="0.002"/>
  <system-out/>
</testsuite> <!-- Api_tescase.TC004_Post_Employes_record_updated -->
